version: 2
jobs:
  build:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run test:e2e:ci
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots
      - store_test_results:
          path: test-results.xml
      - run: npm run build
      - store_artifacts:
          path: dist
